name       : libsolv
version    : 0.7.2
release    : 3
source     :
    - https://github.com/openSUSE/libsolv/archive/0.7.2.tar.gz : 8aa19c6726789f500e7301180608d09e6af99d75a2d336435686ae438bd9933e
license    : BSD-3-Clause
component  : programming.library
summary    : Package dependency solver
description: |
    A free package dependency solver using satisfiability algorithm. The
    library is based on two major, but independent, blocks.

    * Using a dictionary approach to store and retrieve package and
      dependency information.

    * Using satisfiability, a well known and researched topic, for
      resolving package dependencies.

builddeps  :
    - pkgconfig(rpm)
    - bzip2-devel
    - db5-devel
setup      : |
    mkdir libsolv-build
    pushd libsolv-build
    # Using the FEDORA definition so that libdnf will have the correct basic setup
    %cmake -DFEDORA=1 \
        -DENABLE_APPDATA=ON \
        -DENABLE_COMPS=ON \
        -DENABLE_COMPLEX_DEPS=ON \
        -DENABLE_BZIP2_COMPRESSION=ON \
        -DENABLE_RPMDB=ON \
        -DENABLE_RPMDB_BYRPMHEADER=ON \
        -DENABLE_RPMMD=ON \
        -DWITH_LIBXML2=ON \
        -DENABLE_LZMA_COMPRESSION=ON ..
build      : |
    %make -C libsolv-build
install    : |
    %make_install -C libsolv-build

check      : |
    pushd libsolv-build
    ctest ..
    popd
